[package]
name = "aoc_2022"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pb_01"
path = "2022/rust/pb_01.rs"

[[bin]]
name = "pb_02"
path = "2022/rust/pb_02.rs"

[[bin]]
name = "pb_03"
path = "2022/rust/pb_03.rs"

[[bin]]
name = "pb_04"
path = "2022/rust/pb_04.rs"

[dependencies]
